//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSignal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dep
    {
        public tbl_Dep()
        {
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int DepID { get; set; }
        public string DepName { get; set; }
    
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
